### ISSUE TITLE
Artifact Name Clarification

### ISSUE THREAD

**Issue by MMStandley** [secure-cake/win-mal-investigations#1]
Very minor... I noticed under Acquire Artifacts you have Windows.System.StartupItems, however in Velociraptor it is listed as Windows.Sys.StartupItems. :) That's all. Thanks for all your work!

**Comment by secure-cake** [comment]
You are officially nominated as my editor! The pay isn't great...but there is a ton of appreciation! Thank you - updated!

**Comment by secure-cake** [comment]
Closing.
